# Generated by Django 3.0.2 on 2020-01-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialism_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_name', models.CharField(max_length=30)),
                ('background_file', models.FileField(upload_to='')),
                ('specialism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Specialism')),
            ],
        ),
    ]
