# Generated by Django 3.0.2 on 2020-01-25 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialismLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialism_logo_name', models.CharField(max_length=30)),
                ('specialism_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='backgroundimage',
            name='background_name',
        ),
        migrations.AddField(
            model_name='specialism',
            name='specialism_logo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generator.SpecialismLogo'),
            preserve_default=False,
        ),
    ]
